controllers_admin:
    resource:
        path: ../src/Controller/Admin
        namespace: App\Controller\Admin
    type: attribute

controllers_api:
    prefix: /api/v1
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute
